-- Seeds: Categorias
INSERT INTO toolCategories (categoryName, slug, description, iconClass, sortOrder, isActive) VALUES
('Perfuração', 'perfuracao', 'Furadeiras, parafusadeiras e marteletes para perfuração em concreto, madeira e metal.', 'bi bi-gear-wide-connected', 1, TRUE),
('Corte', 'corte', 'Serras, esmerilhadeiras e equipamentos de corte para diversos materiais.', 'bi bi-scissors', 2, TRUE),
('Medição', 'medicao', 'Trenas, níveis, telêmetros e instrumentos de medição de precisão.', 'bi bi-rulers', 3, TRUE),
('Elétrica', 'eletrica', 'Ferramentas elétricas em geral: fios, cabos, multímetros e equipamentos.', 'bi bi-lightning', 4, TRUE),
('Hidráulica', 'hidraulica', 'Mangueiras, conectores e ferramentas para sistemas hidráulicos.', 'bi bi-water', 5, TRUE),
('Pintura', 'pintura', 'Pistolas, rolos, pincéis e equipamentos para pintura profissional.', 'bi bi-paint-bucket', 6, TRUE),
('Jardinagem', 'jardinagem', 'Cortadores de grama, podadores e ferramentas para jardinagem.', 'bi bi-flower1', 7, TRUE),
('Segurança', 'seguranca', 'EPIs, capacetes, cintos de segurança e equipamentos de proteção.', 'bi bi-shield-check', 8, TRUE);

-- Seeds: Ferramentas
INSERT INTO tools (categoryId, toolName, slug, brand, model, description, dailyPrice, depositAmount, totalStock, availableStock, minRentalDays, maxRentalDays, coverImageUrl, status, isFeatured) VALUES
((SELECT categoryId FROM toolCategories WHERE slug = 'perfuracao'), 'Furadeira de Impacto 800W', 'furadeira-impacto-800w', 'Bosch', 'GBH 2-24 RE', 'Furadeira de impacto profissional com 800W de potência, mandril autoajustável e sistema antivibração. Ideal para concreto, aço e madeira.', 45.00, 200.00, 10, 10, 1, 15, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Furadeira+de+Impacto', 'available', TRUE),
((SELECT categoryId FROM toolCategories WHERE slug = 'perfuracao'), 'Parafusadeira sem Fio 12V', 'parafusadeira-sem-fio-12v', 'Makita', 'DF333D', 'Parafusadeira a bateria 12V com carregador incluso, 2 baterias e maleta. Perfeita para montagem de móveis e drywall.', 35.00, 150.00, 8, 8, 1, 10, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Parafusadeira+12V', 'available', TRUE),
((SELECT categoryId FROM toolCategories WHERE slug = 'perfuracao'), 'Martelete Rompedor 1700W', 'martelete-rompedor-1700w', 'DeWalt', 'D25980', 'Martelete rompedor profissional 1700W com impacto de 62J. Para demolição de concreto e alvenaria pesada.', 120.00, 500.00, 3, 3, 1, 20, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Martelete+Rompedor', 'available', TRUE),

((SELECT categoryId FROM toolCategories WHERE slug = 'corte'), 'Esmerilhadeira Angular 7"', 'esmerilhadeira-angular-7', 'Bosch', 'GWS 1800', 'Esmerilhadeira angular profissional 1800W com disco de 7 polegadas. Para corte e desbaste de metal e concreto.', 50.00, 200.00, 12, 12, 1, 15, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Esmerilhadeira+Angular', 'available', TRUE),
((SELECT categoryId FROM toolCategories WHERE slug = 'corte'), 'Serra Mármore 1800W', 'serra-marmore-1800w', 'Makita', '4100RH', 'Serra mármore profissional 1800W com guia laser e corte profundo. Para pisos, azulejos e granito.', 65.00, 250.00, 5, 5, 1, 15, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Serra+Marmore', 'available', TRUE),
((SELECT categoryId FROM toolCategories WHERE slug = 'corte'), 'Serra Circular 1800W', 'serra-circular-1800w', 'DeWalt', 'DWE575', 'Serra circular profissional 1800W com 7-1/4 polegadas, corte profundo e guia laser. Para madeira e derivados.', 55.00, 200.00, 7, 7, 1, 15, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Serra+Circular', 'available', TRUE),

((SELECT categoryId FROM toolCategories WHERE slug = 'medicao'), 'Trena Laser 50m', 'trena-laser-50m', 'Bosch', 'GLM 50-27', 'Trena a laser profissional com alcance de 50m, precisão de 1.5mm e display iluminado. Mede distâncias, áreas e volumes.', 40.00, 150.00, 6, 6, 1, 10, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Trena+Laser', 'available', TRUE),
((SELECT categoryId FROM toolCategories WHERE slug = 'medicao'), 'Nível Digital 60cm', 'nivel-digital-60cm', 'Stabila', '19648', 'Nível digital eletrônico de 60cm com precisão de 0.1°, display LCD e alarme sonoro. Para nivelamento profissional.', 25.00, 100.00, 8, 8, 1, 10, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Nivel+Digital', 'available', TRUE),
((SELECT categoryId FROM toolCategories WHERE slug = 'medicao'), 'Telêmetro Ultrassônico', 'telemetro-ultrassonico', 'Stanley', 'TLM99', 'Telêmetro ultrassônico digital com alcance de 30m, cálculo de área e volume. Compacto e fácil de usar.', 20.00, 80.00, 5, 5, 1, 7, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Telemetro', 'available', FALSE),

((SELECT categoryId FROM toolCategories WHERE slug = 'eletrica'), 'Multímetro Digital', 'multimetro-digital', 'Fluke', '117', 'Multímetro digital profissional True-RMS com medição de tensão, corrente, resistência e continuidade. Para elétrica predial e industrial.', 30.00, 120.00, 10, 10, 1, 10, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Multimetro+Digital', 'available', TRUE),
((SELECT categoryId FROM toolCategories WHERE slug = 'eletrica'), 'Cortador de Pisos Elétrico 1500W', 'cortador-pisos-eletrico-1500w', 'Makita', '4100W', 'Cortador de pisos elétrico 1500W com sistema de refrigeração a água e guia ajustável. Para cerâmica e porcelanato.', 70.00, 300.00, 4, 4, 1, 15, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Cortador+de+Pisos', 'available', FALSE),
((SELECT categoryId FROM toolCategories WHERE slug = 'eletrica'), 'Detector de Tensão Sem Contato', 'detector-tensao-sem-contato', 'Fluke', '1AC-A1', 'Detector de tensão sem contato com alarme visual e sonoro. Detecta de 90V a 1000V AC. Essencial para segurança elétrica.', 15.00, 50.00, 15, 15, 1, 7, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Detector+de+Tensao', 'available', FALSE),

((SELECT categoryId FROM toolCategories WHERE slug = 'pintura'), 'Pistola de Pintura HVLP 600W', 'pistola-pintura-hvlp-600w', 'Wagner', 'W 550', 'Pistola de pintura HVLP 600W com regulagem de fluxo e bicos intercambiáveis. Para pintura de paredes, móveis e metais.', 60.00, 250.00, 5, 5, 1, 10, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Pistola+de+Pintura', 'available', TRUE),
((SELECT categoryId FROM toolCategories WHERE slug = 'pintura'), 'Lixadeira Orbital 300W', 'lixadeira-orbital-300w', 'Bosch', 'PEX 300 AE', 'Lixadeira orbital aleatória 300W com coletor de pó e velcro para discos. Para acabamento fino em madeira e massa.', 30.00, 100.00, 8, 8, 1, 10, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Lixadeira+Orbital', 'available', FALSE),

((SELECT categoryId FROM toolCategories WHERE slug = 'hidraulica'), 'Máquina de Cortar Tubos 1200W', 'maquina-cortar-tubos-1200w', 'Ridgid', '1210', 'Máquina de cortar tubos profissional 1200W com suporte para tubos de até 4 polegadas. Para encanamento e hidráulica.', 85.00, 350.00, 3, 3, 1, 15, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Cortar+Tubos', 'available', TRUE),
((SELECT categoryId FROM toolCategories WHERE slug = 'hidraulica'), 'Desentupidora Elétrica 800W', 'desentupidora-eletrica-800w', 'Roto-Rooter', 'RR-500', 'Desentupidora elétrica 800W com cabo de 15m e pontas intercambiáveis. Para pias, ralos e tubulações.', 55.00, 200.00, 4, 4, 1, 10, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Desentupidora', 'available', FALSE),

((SELECT categoryId FROM toolCategories WHERE slug = 'jardinagem'), 'Cortador de Grama Elétrico 1200W', 'cortador-grama-eletrico-1200w', 'Tramontina', 'G1200', 'Cortador de grama elétrico 1200W com 30cm de largura de corte, coletor e regulagem de altura. Para jardins residenciais.', 40.00, 150.00, 6, 6, 1, 10, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Cortador+de+Grama', 'available', TRUE),
((SELECT categoryId FROM toolCategories WHERE slug = 'jardinagem'), 'Roçadeira 43cc', 'rocadeira-43cc', 'Stihl', 'FS 45', 'Roçadeira a gasolina 43cc com cabeçote de nylon e lâmina. Para capim alto e mato em terrenos grandes.', 60.00, 250.00, 5, 5, 1, 10, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Rocadeira', 'available', FALSE),

((SELECT categoryId FROM toolCategories WHERE slug = 'seguranca'), 'Kit EPI Completo', 'kit-epi-completo', '3M', 'KIT-100', 'Kit de EPI completo: capacete, óculos, protetor auricular, luvas e cinto de segurança. Certificado CA.', 25.00, 80.00, 20, 20, 1, 30, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Kit+EPI', 'available', TRUE),
((SELECT categoryId FROM toolCategories WHERE slug = 'seguranca'), 'Cinto de Segurança Paraquedista', 'cinto-seguranca-paraquedista', 'MSA', 'V-Fit', 'Cinto de segurança tipo paraquedista com fivela dupla e ponto de ancoragem dorsal. Para trabalho em altura.', 35.00, 150.00, 8, 8, 1, 20, 'https://placehold.co/600x400/1a1a2e/ffffff?text=Cinto+Seguranca', 'available', FALSE);
